source "${BASH_SOURCE%/*}/include/jethome_common.inc"

LINUXFAMILY=jethubj80
CPUMAX=1200000

BOOTSCRIPT="boot-jethubj80.cmd:boot.cmd"
BOOTCONFIG="jethub_j80_v1_defconfig"


family_tweaks()
{
	:
}

uboot_custom_postprocess()
{
	uboot_gxl_postprocess $SRC/cache/sources/jethub-aml-tools gxl
}
