name: Nightly builds

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: jethome-ru/build-armbian/.github/workflows/beta-build.yml@main
    with:
      buildbranch: nightly
    secrets:
      token: ${{ secrets.TOKEN }}
      SSHKEY: ${{ secrets.SSHKEY }}
      SSHKNOWNHOSTS: ${{ secrets.SSHKNOWNHOSTS }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
